version: 1.0.{build}
  image:
    #- Visual Studio 2015
    - Visual Studio 2017

  platform:
    #- x86
    - x86_64

  configuration:
    #- Debug
    - Release

  install:
    - cmmd: set PATH=%PATH%;%PYTHON%/Scripts
    - cmmd: pip install conan
    - cmmd: conan user

  build_script:
    - cmmd: mkdir build && cd build
    - cmmd: conan install -b missing -s compiler='Visual Studio' -s compiler.version=15 ..
    - cmmd: cmake -G 'Visual Studio 15 2017 Win64' ..
    - cmmd: cmake --build . --config Release

  test_script:
    - cmmd: ctest -C Release -V
