version: 1.0.{build}

image:
  - Visual Studio 2015
  #- Visual Studio 2017

platform:
  #- x86
  - x86_64

configuration:
  - Debug
  - Release

cache:
  - '%USERPROFILE%\.conan'

install:
  - echo %PATH%
  - pip install conan
  - conan user
  - conan config set general.user_home_short=None

build_script:
  - mkdir build && cd build
  - conan install -b missing -s build_type "%CONFIGURATION%" -s compiler="Visual Studio" -s compiler.version=14 ..
  - cmake -G "Visual Studio 14 2015 Win64" ..
  - cmake --build . --config "%CONFIGURATION%"

test_script:
  - ctest -C "%CONFIGURATION%" -V
