version: 1.0.{build}

image:
  - Visual Studio 2015
  #- Visual Studio 2017

platform:
  - x86
  - x64

configuration:
  - Debug
  - Release

cache:
  - '%USERPROFILE%\.conan'

install:
  - echo %PATH%
  - pip install conan
  - conan user
  - conan config set general.user_home_short=None
  - if "%PLATFORM%"=="x64" (
      set CONAN_ARCH=x86_64 &
      set CMAKE_ARCH=x64
    ) else (
      set CONAN_ARCH=x86 &
      set CMAKE_ARCH=Win32
    )

build_script:
  - mkdir build && cd build
  - conan install -b missing -s build_type=%CONFIGURATION% -s compiler="Visual Studio" -s compiler.version=14 -s arch=%CONAN_ARCH% ..
  - cmake -G "Visual Studio 14 2015" -A %CMAKE_ARCH% ..
  - cmake --build . --config %CONFIGURATION%

test_script:
  - ctest -C %CONFIGURATION% -V
