version: "{build}"

image:
  - Visual Studio 2019
  - Visual Studio 2017

configuration:
  - Debug
  - Release

platform:
  - x86
  - x64

environment:
  VCPKG_ROOT: C:\Tools\vcpkg
  PATH: C:\Python38-x64;C:\Python38-x64\Scripts;%PATH%
  matrix:
    - BUILD_SHARED_LIBS: "ON"
    - BUILD_SHARED_LIBS: "OFF"

matrix:
  fast_finish: true
  exclude:
    - image: Visual Studio 2019
      configuration: Release
      platform: x86
    - image: Visual Studio 2019
      configuration: Debug
      platform: x64
    - image: Visual Studio 2017
      configuration: Release
      platform: x64
    - image: Visual Studio 2017
      configuration: Debug
      platform: x86
    - configuration: Debug
      BUILD_SHARED_LIBS: "ON"
    - configuration: Release
      BUILD_SHARED_LIBS: "OFF"

cache:
  - '%VCPKG_ROOT%\installed -> vcpkgfile.txt'
  - '%LOCALAPPDATA%\pip\Cache -> requirements.txt'

install:
  - py -m pip install -U -r requirements.txt
  - if "%PLATFORM%"=="x86" (
      set "VCPKG_DEFAULT_TRIPLET=x86-windows" &
      set "CMAKE_GENERATOR_PLATFORM=Win32"
    )
  - if "%PLATFORM%"=="x64" (
      set "VCPKG_DEFAULT_TRIPLET=x64-windows" &
      set "CMAKE_GENERATOR_PLATFORM=x64"
    )
  - if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2019" (
      set "CMAKE_GENERATOR=Visual Studio 16 2019"
    )
  - if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2017" (
      set "CMAKE_GENERATOR=Visual Studio 15 2017"
    )
  - if "%CONFIGURATION%"=="Debug" (
      set "BUILD_BENCHMARKS=OFF"
    )
  - if "%CONFIGURATION%"=="Release" (
      set "BUILD_BENCHMARKS=ON"
    )
  - set

build_script:
  - '%VCPKG_ROOT%\vcpkg update'
  - '%VCPKG_ROOT%\vcpkg install @vcpkgfile.txt'
  - mkdir build && cd build
  - cmake ..
      -DBUILD_SHARED_LIBS=%BUILD_SHARED_LIBS%
      -DCMAKE_TOOLCHAIN_FILE=%VCPKG_ROOT%\scripts\buildsystems\vcpkg.cmake
      -DBUILD_TESTING=ON
      -DBUILD_BENCHMARKS=%BUILD_BENCHMARKS%
      -DBUILD_EXAMPLES=ON
      -Ddebug_dynamic_deps=ON
  - cmake --build . --verbose --config %CONFIGURATION%

test_script:
  - ctest -C %CONFIGURATION% -V
  - cmake --build . --verbose --config %CONFIGURATION% --target install

artifacts:
  - path: build\**\*.log
    name: logs
  - path: build\**\*.xml
    name: test_results

skip_commits:
  files:
    - .travis.yml
