version: 1.0.{build}

image:
  #- Visual Studio 2015
  - Visual Studio 2017

platform:
  #- x86
  - x86_64

configuration:
  #- Debug
  - Release

install:
  - echo %PATH%
  - set PATH=%PATH%;%PYTHON%/Scripts
  - pip install conan
  - conan user

build_script:
  - mkdir build && cd build
  - conan install -b missing -s compiler='Visual Studio' -s compiler.version=15 ../
  - cmake -G 'Visual Studio 15 2017 Win64' ..
  - cmake --build . --config Release

test_script:
  - ctest -C Release -V
