version: "{build}"

image:
  - Visual Studio 2019
  - Visual Studio 2017

configuration:
  - Debug
  - Release

platform:
  - x86
  - x64

environment:
  VCPKG_ROOT: C:\Tools\vcpkg
  VCPKG_DEFAULT_TRIPLET: "%PLATFORM%-windows"
  PATH: C:\Python38-x64;C:\Python38-x64\Scripts;%PATH%
  VERBOSE: 1
  matrix:
    - BUILD_SHARED_LIBS: "ON"
    - BUILD_SHARED_LIBS: "OFF"

matrix:
  fast_finish: true
  exclude:
    - image: Visual Studio 2019
      configuration: Release
      platform: x86
    - image: Visual Studio 2019
      configuration: Debug
      platform: x64
    - image: Visual Studio 2017
      configuration: Release
      platform: x64
    - image: Visual Studio 2017
      configuration: Debug
      platform: x86
    - configuration: Debug
      BUILD_SHARED_LIBS: "ON"
    - configuration: Release
      BUILD_SHARED_LIBS: "OFF"

cache:
  - '%VCPKG_ROOT%\installed -> vcpkgfile.txt'
  - '%LOCALAPPDATA%\pip\Cache -> requirements.txt'

install:
  - py -m pip install -U -r requirements.txt
  - if "%PLATFORM%"=="x86" (
      set "CMAKE_GENERATOR_PLATFORM=Win32"
    ) else if "%PLATFORM%"=="x64" (
      set "CMAKE_GENERATOR_PLATFORM=x64"
    )
  - if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2019" (
      set "CMAKE_GENERATOR=Visual Studio 16 2019"
    ) else if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2017" (
      set "CMAKE_GENERATOR=Visual Studio 15 2017"
    )
  - if "%CONFIGURATION%"=="Debug" (
      set "BUILD_BENCHMARKS=OFF"
    ) else if "%CONFIGURATION%"=="Release" (
      set "BUILD_BENCHMARKS=ON"
    )
  - cmake -E environment
  - cmake -E capabilities

build_script:
  - cmake --warn-uninitialized
      -D package_manager=vcpkg
      -D build_type=%CONFIGURATION%
      -D update=ON
      -P scripts\setup.cmake

test_script:
  - cmake --warn-uninitialized
      -D package_manager=vcpkg
      -D cmake_config=%CONFIGURATION%
      -D cmake_shared=%BUILD_SHARED_LIBS%
      -D testing=ON
      -D benchmark=%BUILD_BENCHMARKS%
      -D examples=ON
      -D rpaths=ON
      -D install=ON
      -P scripts\run.cmake

artifacts:
  - path: build\**\*.log
    name: logs
  - path: build\**\*.xml
    name: test_results

skip_commits:
  files:
    - .travis.yml
