version: "{build}"

image:
  # - Visual Studio 2015
  - Visual Studio 2017

configuration:
  - Debug
  - Release

platform:
  - x86
  - x64

environment:
  VCPKG_ROOT: c:\tools\vcpkg
  matrix:
    - BUILD_SHARED_LIBS: ON
    - BUILD_SHARED_LIBS: OFF

matrix:
  exclude:
    # - image: Visual Studio 2015
    #   configuration: Release
    #   platform: x86
    # - image: Visual Studio 2015
    #   configuration: Debug
    #   platform: x64
    - image: Visual Studio 2017
      configuration: Release
      platform: x64
    - image: Visual Studio 2017
      configuration: Debug
      platform: x86

cache:
  - '%VCPKG_ROOT%\installed'
  - '%LOCALAPPDATA%\pip\Cache'

install:
  - python -m pip install -U -r requirements.txt
  - if "%PLATFORM%"=="x86" (
      set "VCPKG_ARCH=x86" &
      set "CMAKE_ARCH=Win32"
    )
  - if "%PLATFORM%"=="x64" (
      set "VCPKG_ARCH=x64" &
      set "CMAKE_ARCH=x64"
    )
  # - if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2015" (
  #     set "COMPILER_VERSION=14" &
  #     set CMAKE_GENERATOR="Visual Studio 14 2015"
  #   )
  - if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2017" (
      set "COMPILER_VERSION=15" &
      set CMAKE_GENERATOR="Visual Studio 15 2017"
    )

build_script:
  - mkdir build && cd build
  - vcpkg install @..\vcpkgfile.txt
      --triplet %VCPKG_ARCH%-windows
  - cmake ..
      -B.
      -G%CMAKE_GENERATOR%
      -A%CMAKE_ARCH%
      -DBUILD_SHARED_LIBS=%BUILD_SHARED_LIBS%
      -DCMAKE_TOOLCHAIN_FILE=%VCPKG_ROOT%\scripts\buildsystems\vcpkg.cmake
      -Ddebug_dynamic_deps=ON
  - cmake --build . --config %CONFIGURATION%

test_script:
  - ctest -C %CONFIGURATION% -V
  - cmake --build . --config %CONFIGURATION% --target install
  - cmake --build . --config %CONFIGURATION% --target uninstall

artifacts:
  - path: 'build/**/*.log'
    name: logs
  - path: 'build/**/*.xml'
    name: test_results
