version: 1.0.{build}

image:
  #- Visual Studio 2015
  - Visual Studio 2017

platform:
  #- x86
  - x86_64

configuration:
  #- Debug
  - Release

install:
  - cmd: set PATH=%PATH%;%PYTHON%/Scripts
  - cmd: pip install conan
  - cmd: conan user

build_script:
  - cmd: mkdir build && cd build
  - cmd: conan install -b missing -s compiler='Visual Studio' -s compiler.version=15 ..
  - cmd: cmake -G 'Visual Studio 15 2017 Win64' ..
  - cmd: cmake --build . --config Release

test_script:
  - cmd: ctest -C Release -V
