image: gumienny/gcc:6

pipelines:
  custom:
    run-ci:
      - parallel:
          # - step:
          #     name: Build and test
          #     script:
          #       - cmake .
          #       - make -j $(nproc)
          #       - ctest -j $(nproc) -D ExperimentalTest
          # - step:
          #     name: Build and test coverage
          #     script:
          #       - apt-get update && apt-get install -y gcovr
          #       - cmake -D build_coverage=ON .
          #       - make -j $(nproc)
          #       - ctest -j $(nproc) -D ExperimentalTest
          #       - ctest -j $(nproc) -D ExperimentalCoverage
          - step:
              name: Build and test memcheck
              script:
                - cmake -D CMAKE_BUILD_TYPE=Debug .
                - make -j $(nproc)
                - ctest -j $(nproc) -D ExperimentalMemCheck
          # - step:
          #     name: Generate documentation
          #     script:
          #       - apt-get update && apt-get install -y doxygen graphviz
          #       - cmake -D BUILD_TESTING=OFF .
          #       - make doc
