function(enable_diagnostics_color)
    foreach(language IN LISTS ARGN)
        if(CMAKE_${language}_COMPILER_ID STREQUAL "GNU")
            if(CMAKE_GENERATOR STREQUAL "Ninja")
                add_compile_options($<$<COMPILE_LANGUAGE:${language}>:-fdiagnostics-color>)
            else()
                add_compile_options($<$<COMPILE_LANGUAGE:${language}>:-fdiagnostics-color=auto>)
            endif()
        elseif(CMAKE_${language}_COMPILER_ID MATCHES "Clang")
            if(CMAKE_GENERATOR STREQUAL "Ninja")
                add_compile_options($<$<COMPILE_LANGUAGE:${language}>:-fcolor-diagnostics>)
            endif()
        endif()
    endforeach()
endfunction()

enable_diagnostics_color(CXX)
