set(${PROJECT_NAME}_sanitizer "" CACHE STRING
    "Sanitizer types: thread, address, leak, memory, undefined.")

set(${PROJECT_NAME}_fuzzer "" CACHE STRING
    "Fuzzer types: fuzzer.")

if(${PROJECT_NAME}_sanitizer)
    if(${PROJECT_NAME}_fuzzer)
        list(APPEND sanitizers ${${PROJECT_NAME}_fuzzer})
    endif()
    list(APPEND sanitizers ${${PROJECT_NAME}_sanitizer})
    if(MSVC)
        message(FATAL_ERROR "${PROJECT_NAME}_sanitizer not supported yet for MSVC")
    else()
        string(APPEND CMAKE_C_FLAGS " -fsanitize=$<JOIN:${sanitizers},$<COMMA>>")
        string(APPEND CMAKE_CXX_FLAGS " -fsanitize=$<JOIN:${sanitizers},$<COMMA>>")
    endif()
    if(${PROJECT_NAME}_sanitizer STREQUAL thread)
        set(MEMORYCHECK_TYPE ThreadSanitizer)
    elseif(${PROJECT_NAME}_sanitizer STREQUAL address)
        set(MEMORYCHECK_TYPE AddressSanitizer)
    elseif(${PROJECT_NAME}_sanitizer STREQUAL leak)
        set(MEMORYCHECK_TYPE LeakSanitizer)
    elseif(${PROJECT_NAME}_sanitizer STREQUAL memory)
        set(MEMORYCHECK_TYPE MemorySanitizer)
    elseif(${PROJECT_NAME}_sanitizer STREQUAL undefined)
        set(MEMORYCHECK_TYPE UndefinedBehaviorSanitizer)
    else()
        message(FATAL_ERROR
            "${PROJECT_NAME}_sanitizer=$<JOIN:${sanitizers},$<COMMA>> not supported yet")
    endif()
endif()
